### ISSUE TITLE
Fix how words are being split

### ISSUE THREAD

**Issue by atreib** [gustavoguichard/string-ts#54]
I noticed the following:

- When "prev2", the `Words` type is correctly splitting to `[prev, 2]`
- When "preV2", the `Words` type is **incorrectly** splitting to `[pre, v, 2]`
> (I noticed this while using the `deepSnakeKeys()` function)

Per what I understand, the 2nd example ("preV2") should be split to `[pre, V2]`.
What do you think?

UPDATE:

1. If we take a look at how `lodash` handles the `snakeCase()` function, it is exactly as `string-ts` handles it (the `pre_v_2` example). And here is a sandbox: https://codesandbox.io/s/lodash-camel-vs-snake-case-d37djv
2. It's hard to find a "final definition", but since snake_case is very related to Ruby, I took a look at this [Ruby style guide](https://github.com/rubocop/ruby-style-guide#snake-case-symbols-methods-vars-with-numbers), and there we find "Do not separate numbers from letters", so I understand that lodash handles it wrongly too...

**Comment by p9f** [comment]
Thanks for the report @atreib!

As you said, I think it is hard to find a final definition. I would not say that snake_case is very related to Ruby, as it is widely use outside of ruby (python, rust, sql, perl, ...). As far as I know, there is no standard commonly agreed (It seems that [rust](https://doc.rust-lang.org/1.0.0/style/style/naming/README.html) is taking the opposite stands for example), so doing as lodash might be a sensible option since we are a js library and not a ruby one?

Also, in your first example - I don't think `prev2` should be parsed as `[prev, 2]` if we where to follow the rubocop style guide, but `[prev2]`?

**Comment by gustavoguichard** [comment]
I wanted to let other people comment on this issue because I think it is a stylistic discussion rather than a fix - that means it might become a breaking change.

Especially if we consider the importance of the `words` method for this library. Changing it might require extensive checking and coverage to guarantee we are not gonna have unwanted side effects.

That said, I'll throw a counter point here. Consider the string "example text 1", which would think would be the preferred snake case transformation: "example_text1" or "example_text_1"? IMHO the later seems to be the expected, and in that case this PR would go in the wrong direction.

But as I said it is a style issue, so I'll let it open so other people can comment for now ;). I'd love to hear more points of views.

**Comment by gustavoguichard** [comment]
I think the question is: should an uppercase letter followed by a number be considered the same word?

"HTML5 Document" -> html5_document seems to make sense.

But html5Document would become html_5_document if we only consider uppercase.

Then, should any number followed by a character be considered the same word?

**Comment by atreib** [comment]
@p9f Good thinking! I haven't looked into other naming conventions...

I thought it was odd when using the `deepSnakeKeys()` function to convert a camelCase object. I have a object like `{ apiV2: null }` which transformed to `{ api_v_2: null }`, and felt odd... But I guess it makes sense to follow lodash definition, thinking on broader scenarios and the whole JS community.

Thanks for the discussion, folks!

**Comment by gustavoguichard** [comment]
I'll close this issue for now, feel free to re-open it if anyone wants to discuss it further.
I appreciate your awesome contribution nonetheless, @atreib ❤️

**Comment by gustavoguichard** [comment]
I'll close this issue for now, feel free to re-open it if anyone wants to discuss it further.
I appreciate your awesome contribution nonetheless, @atreib ❤️
